declare module "serverline";
declare module "telnet";
declare module "@kernel:base";
declare module "@commands:executor";
declare module "@commands:create";
declare module "@commands:ls";
declare module "@commands:save";
declare module "@builtin:systemd";
declare module "@builtin:sshd";
declare module "@echo off";